### ISSUE TITLE
GL/PL aus Persionio in der Controlling-Ansicht darstellen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#723]
1. **What is the current state?**

- Wenn in Persionio ein falscher oder kein Gildenlead oder PL eingetragen sind, so wird das in MEGA nicht dagestellt.

2. **What is the desired state?**
Fehlende, oder falsche Angeben sollen in MEGA beim User für die PLs ersichtlich sein. Im Dashboard ist es nicht erforderlich (kann optional jedoch gemacht werden).

AC:
- [ ] Wenn in Personio ein PL mit "NA" eingetragen sind, so ist dieser im Rollenkonzept (und somit auch als Fehler) zu ignorieren
- [ ] Wenn in Personio ein GL mit "NA" eingetragen sind, so ist dieser im Rollenkonzept (und somit auch als Fehler) zu ignorieren
- [ ] Wenn in Persionio ein PL oder GL nicht gemappt werden kann (zB Tippfehler)
- [ ] Wenn ein PL eingetragen ist, soll dieser in einem Pop-Up beim Mouseover dargestellt werden
- [ ] Wenn ein GL eingetragen ist, soll dieser in einem Pop-Up beim Mouseover dargestellt werden

Siehe auch #721
